// Mocks generated by Mockito 5.4.4 from annotations
// in news_api/test/presentation/news_list/bl/news_list_observer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_api/domain/models/article.dart' as _i4;
import 'package:news_api/domain/repositories/article_repo.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ArticleRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRepo extends _i1.Mock implements _i2.ArticleRepo {
  @override
  _i3.Future<List<_i4.Article>> getArticlesAPI({required int? page}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticlesAPI,
          [],
          {#page: page},
        ),
        returnValue: _i3.Future<List<_i4.Article>>.value(<_i4.Article>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Article>>.value(<_i4.Article>[]),
      ) as _i3.Future<List<_i4.Article>>);

  @override
  _i3.Future<List<_i4.Article>> getArticlesDB() => (super.noSuchMethod(
        Invocation.method(
          #getArticlesDB,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Article>>.value(<_i4.Article>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Article>>.value(<_i4.Article>[]),
      ) as _i3.Future<List<_i4.Article>>);
}
